//! Project + Instruction types produced by the LLM.
//!
//! A Project is a complete firmware program: wiring guide + setup + loop.

use serde::Deserialize;
use heapless::{String, Vec};

/// Single VM instruction.
#[derive(Debug, Deserialize, Clone)]
#[serde(rename_all = "snake_case")]
pub enum Instruction {
    /// Configure pin as digital output.
    ConfigOutput { pin: u8 },
    /// Configure pin as digital input.
    ConfigInput { pin: u8 },
    /// Configure pin for PWM (LEDC).
    ConfigPwm { pin: u8 },
    /// Drive output pin HIGH.
    SetHigh { pin: u8 },
    /// Drive output pin LOW.
    SetLow { pin: u8 },
    /// Set PWM duty cycle (0-255).
    SetPwm { pin: u8, duty: u8 },
    /// Read ADC on pin, store in variable.
    ReadAdc { pin: u8, var: String<8> },
    /// Read digital level on pin, store in variable.
    ReadDigital { pin: u8, var: String<8> },
    /// Sleep for N milliseconds.
    Delay { ms: u32 },
    /// Set variable to constant value.
    SetVar { var: String<8>, value: u16 },
    /// No-op marker for jumps.
    Label { name: String<16> },
    /// Unconditional jump to label.
    Jump { label: String<16> },
    /// Jump to label if var < value.
    JumpIfLt { var: String<8>, value: u16, label: String<16> },
    /// Jump to label if var > value.
    JumpIfGt { var: String<8>, value: u16, label: String<16> },
    /// Jump to label if var == value.
    JumpIfEq { var: String<8>, value: u16, label: String<16> },
}

/// A complete project generated by the LLM.
#[derive(Debug, Deserialize, Clone)]
pub struct Project {
    /// Human-readable wiring guide sent back to the user.
    pub wiring_instructions: String<512>,
    /// One-sentence summary.
    pub description: String<256>,
    /// One-time setup instructions (executed once on load).
    pub setup: Vec<Instruction, 16>,
    /// Instructions that repeat in a loop.
    pub loop_body: Vec<Instruction, 32>,
    /// Delay between loop iterations in milliseconds.
    pub interval_ms: u32,
}

impl Project {
    pub fn new() -> Self {
        Self {
            wiring_instructions: String::new(),
            description: String::new(),
            setup: Vec::new(),
            loop_body: Vec::new(),
            interval_ms: 1000,
        }
    }
}
